<?php
//@codingStandardsIgnoreFile

/** @var \Mirasvit\Blog\Block\Post\PostList $block */
$collection = $block->getPostCollection();
?>

<?php if ($collection->count()): ?>
    <div class="blog__post-list-wrapper">
        <ol class="blog__post-list">
            <?php /** @var \Mirasvit\Blog\Model\Post $post */ ?>
            <?php foreach ($collection as $post): ?>
                <li class="blog__post-item">                   

                    <div class="blog__post-excerpt" itemprop="text">
					<div class="blog__post_img-cls">
                        <?php if ($post->getFeaturedImageUrl() && $post->getFeaturedShowOnHome()): ?>
                            <a href="<?= $post->getUrl() ?>">
                                <img src="<?= $post->getFeaturedImageUrl() ?>" alt="<?= $block->getFeaturedAlt($post) ?>"/>
                            </a>
                        <?php endif ?>
                    </div>
					<header class="blog__post-header">
                        <h2 class="blog__post-title" itemprop="headline">
                            <a href="<?= $post->getUrl() ?>" rel="bookmark"><?= $post->getName() ?></a>
                        </h2>

                        <?= $block->getPostMetaHeader($post)->toHtml() ?>
                    </header>
					<div class="blog__post_content-cls">
                        <?= $post->getShortContent() ?>
                    </div>
                        <a class="read-more" href="<?= $post->getUrl() ?>"><?= __('Read more') ?>
						<i class="fa fa-angle-double-right" aria-hidden="true"></i></a>
                    </div>
					

                    <?php /* <?= $block->getPostMetaFooter($post)->toHtml() ?> */?>
                </li>
            <?php endforeach ?>
        </ol>

        <?php echo $block->getToolbarHtml() ?>
    </div>
<?php else: ?>
    <div class="message notice">
        <div><?= __('There are no posts available for this category.') ?></div>
    </div>
<?php endif ?>
