<?php
/**
 * Solwin Infotech
 * Solwin Featured Product Extension
 * 
 * @category   Solwin
 * @package    Solwin_FeaturedPro
 * @copyright  Copyright © 2006-2016 Solwin (https://www.solwininfotech.com)
 * @license    https://www.solwininfotech.com/magento-extension-license/
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
$helper = $this->helper('Solwin\FeaturedPro\Helper\Data');
$enableModule = $helper->getConfigValue('featuredpro_settings/featured_products/enable');
if ($enableModule) {

    $block_title = $this->getData('widget_title');

    $_productCollection = $block->getLoadedProductCollection();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $imageBlock = $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
    ?>
    <?php if (!$_productCollection->count()): ?>
        <div class="message info empty"><div><?php echo __('We can\'t find products matching the selection.') ?></div></div>
    <?php else: ?>
        <?php
        if ($block->getMode() == 'grid') {
            $viewMode = 'grid';
            $image = 'category_page_grid';
            $showDescription = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        } else {
            $viewMode = 'list';
            $image = 'category_page_list';
            $showDescription = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        }
        $pos = $block->getPositioned();
        $position = '';
        if ($pos != null) {
            $position = ' style="left:' . $block->getVar("{$image}:width") . 'px;'
                    . 'top:' . $block->getVar("{$image}:height") . 'px;"';
        }
        ?>
        <div class="pad-main-bottom wrapper home-featured-pro <?php echo $viewMode; ?> products-<?php echo $viewMode; ?>">
            <div class="home-featured-pro-cls">
                <div class="block-title-main home-cls-title">
                    <h2><?php echo __($block_title); ?></h2>
                    <div class="title-border"></div>
                </div>
                    <?php $iterator = 1; ?>
                <ol class="products list items product-items featuredproduct">
                    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                    <?php foreach ($_productCollection as $_product): ?>
                            <?php echo($iterator++ == 1) ? '<li style="margin-top:20px;" class="item product product-item">' : '</li><li style="margin-top:20px;" class="item product product-item">' ?>
                        <div class="product-item-info" data-container="product-grid">
            <?php // Product Image     ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <span class="product-image-container">
                                    <span style="padding-bottom: 121%;" class="product-image-wrapper">
                                        <?php
                                        $imageUrl = $this->helper('Magento\Catalog\Helper\Image')
                                                ->init($_product, 'product_page_image_large')
                                                ->constrainOnly(FALSE)
                                                ->keepAspectRatio(TRUE)
                                                ->keepFrame(FALSE)
                                                ->resize(270, 371)
                                                ->getUrl();
                                        ?>
                                        <img class="product-image-photo" src="<?php echo $imageUrl; ?>" />
                                    </span>
                                </span>
                            </a>

                            <div class="product details product-item-details">
                                <div style="padding: 0 2px;"><?php echo $block->getProductDetailsHtml($_product); ?></div>
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?php echo $_product->getProductUrl() ?>">
            <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </strong>
                                <?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
            <?php echo $block->getProductPrice($_product) ?>

                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
									    <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                       <form data-role="tocart-form" action="<?php echo $postParams['action']; ?>" method="post">
									    <div class="featured-qty">
										    <select name="qty">
											    <option value="1">1</option>
											    <option value="2">2</option>
											    <option value="3">3</option>
											    <option value="4">4</option>
											    <option value="5">5</option>
											    <option value="6">6</option>
											    <option value="7">7</option>
											    <option value="8">8</option>
											    <option value="9">9</option>
											    <option value="10">10</option>
											</select>
										</div>
                                        <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                                    <input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
                                                    <input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                <?php echo $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                            class="action tocart primary">
                                                        <span><i class="fa fa-shopping-cart" aria-hidden="true"></i><?php echo __('Add to Cart') ?></span>
                                                    </button>
                                                
                                        </div>
										<div class="prod-detail-link"><a href="<?php echo $_product->getProductUrl(); ?>"><i class="fa fa-search" aria-hidden="true"></i></a></div>
										</form>
                                            <?php else: ?>
                                                <?php if ($_product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                    </div>
                                        <?php if ($showDescription): ?>
                                        <div class="product description product-item-description">
                <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>"
                                               class="action more"><?php echo __('Learn More') ?></a>
                                        </div>
            <?php endif; ?>
                                </div>
                            </div>
                        </div>
                        <?php echo($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
        <?php endforeach; ?>
                </ol>
            </div>
        </div>
        <?php if (!$block->isRedirectToCartEnabled()) : ?>
            <script type="text/x-magento-init">
                {
                "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
                }
                }
            </script>
        <?php endif; ?>
    <?php endif; ?>

    <script>
        require(['jquery', 'cpowlcarousel'], function () {
            jQuery(document).ready(function () {
                jQuery(".featuredproduct").owlCarousel({
                    items: 3,					
                    itemsDesktop: [1080, 3],
                    itemsDesktopSmall: [860, 2],
                    itemsTablet: [768, 3],
                    itemsTabletSmall: [639, 2],
                    itemsMobile: [360, 2],
                    pagination: false,
                    navigationText: ["<div class='lft-btn'><i class='fa fa-angle-left'></i></div>", "<div class='rgt-btn'><i class='fa fa-angle-right'></i></div>"],
                    navigation: true,
                });
            });
        });
    </script>
    <?php
}
