<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View*/
?>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5a9e6c219454ddbd"></script>
<div class="social-share">Share:</div>
<div class="addthis_toolbox addthis_default_style">
	 <a class="addthis_button_facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a>
	 <a class="addthis_button_twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a>
	 <a class="addthis_button_google"><i class="fa fa-google-plus" aria-hidden="true"></i></a>
	 <a class="addthis_button_linkedin"><i class="fa fa-linkedin" aria-hidden="true"></i></a> 
</div>
<div class="product-addto-links" data-role="add-to-links">
    <?= $block->getChildHtml() ?>
</div>
