<?php 
    $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
	$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
    $currentStore = $storeManager->getStore();
	$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
	$productCollectionFactory = $objectManager->get('Mirasvit\Blog\Model\ResourceModel\Post\CollectionFactory');
	$collection = $productCollectionFactory->create();
	$collection->addAttributeToSelect('*');
	$collection->addAttributeToFilter('featured_show_on_home',1);
	$collection->setPageSize(3);
    $baseUrl = $currentStore->getBaseUrl();
 ?>
<div class="blog-content-home">
   <div class="block-title-main home-cls-title">
	   <h2>OUR BLOG</h2>
	   <div class="title-border"></div>
   </div>
   <ul class="homepage-blog">
   <?php 
       foreach ($collection as $blogdata) {
		   $ddate=date_create($blogdata->getCreated_at());
		   echo '<li><div class="blog-img"><a href="'.$blogdata->getUrl().'"><img src="'.$mediaUrl.'blog/'.$blogdata->getFeatured_image().'" /></a></div><div class="blog-cont"><div class="blog-title"><a href="'.$blogdata->getUrl().'">'.$blogdata->getName().'</a></div><div class="blog-content">'.$blogdata->getShortContent().'</div><div class="read-more"><a href="'.$blogdata->getUrl().'">Read more<i class="fa fa-angle-double-right" aria-hidden="true">&nbsp;</i></a></div></div><div class="createdat"><span>'.date_format($ddate,"d").'</span><span class="blog-month">'.date_format($ddate,"M").'</span></div></li>';
	 }
   ?>
   </ul>
</div>