<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
	<nav class="navigation" data-action="navigation">
	<div class="left-category-navigation">
		<div class="navigation-cls-title">
		   <div class="category-title"><i class="fa fa-bars" aria-hidden="true"></i>Categories</div>
		   <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('top_left_sidebar')->toHtml(); ?>
		</div>
	</div>
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?= /* @escapeNotVerified */ $_menu ?>
        <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
    </ul>
	<div class="col-freshipping">FREE SHIPPING ON ORDERS OVER $50 <i class="fa fa-truck" aria-hidden="true"></i></div>
</nav>

