<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>
<?php
    $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
	$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
    $currentStore = $storeManager->getStore();
	$baseUrl = $currentStore->getBaseUrl();
 ?>
<label>Get special discounts on your inbox</label>
<form class="form subscribe"
	novalidate
	action="<?php echo $baseUrl.'newsletter/subscriber/new'; ?>"
	method="post"
	data-mage-init='{"validation": {"errorClass": "mage-error"}}'
	id="newsletter-validate-detail">
	<div class="input-box">
			<input name="email" type="email" id="newsletter"
						placeholder="<?= $block->escapeHtmlAttr(__('Enter your email address')) ?>"
						data-validate="{required:true, 'validate-email':true}"/>
			<button class="action subscribe primary btn-news" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit">
			<span><i class="fa fa-envelope-o"></i></span>
		</button>
	</div>
</form>